env: metadrive

env_args:
  discrete_steering_dim: 5
  discrete_throttle_dim: 5
  discrete_action: True

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000