env: metadrive

env_args:
  discrete_steering_dim: 5
  discrete_throttle_dim: 5
  discrete_action: True
  env_name: "bottleneck"

test_greedy: True
test_nepisode: 32
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 500
t_max: 10000
